version: '3.9'

services:
  postgresql:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  company-server-manipulator:
    build: ./
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresql